name: Node.js CI pipeline. Linting, Testing, Building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Modules
        run: npm install
      - name: Build Production Project
        run: npm run build:prod
        if: always()
      - name: Linting Typescript
        run: npm run lint:ts
        if: always()
      - name: Linting CSS
        run: npm run lint:css
        if: always()
      - name: Unit Testing
        run: npm run test:unit
